site:
  title: Документация Jmix
  start_page: jmix:ROOT:intro.adoc
  url: https://docs.jmix.ru/
content:
  sources: 
  - url: ./
    branches:
    - main_ru
    start_path: content
#  - url: https://github.com/haulmont/jmix-frontend.git
#    branches:
#    - master
#    - release_0_9
#    start_path: docs-src/doc-component-repo
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./content/supplemental
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    # start cuba frontend
    manual_platform: 'https://docs.jmix.io/jmix/0.x'
    manual_restApi: 'https://docs.jmix.io/jmix/0.x/rest/index.html'
    manual_studio: 'https://docs.jmix.io/jmix/0.x/studio/index.html'
    restApiSwagger: 'http://files.cuba-platform.com/swagger/7.2'
    compositionGuide: 'https://docs.jmix.io/jmix/0.x/data-model/entities.html#references'
    antDesign_base: 'https://ant.design'
    npm_frontendGenerator: 'https://www.npmjs.com/package/@haulmont/jmix-front-generator'
    npm_cubaReactCore: 'https://www.npmjs.com/package/@haulmont/jmix-react-core'
    npm_cubaReactUi: 'https://www.npmjs.com/package/@haulmont/jmix-react-ui'
    npm_cubaRestJs: 'https://www.npmjs.com/package/@haulmont/jmix-rest'
    forum: 'https://www.cuba-platform.com/discuss/c/jmix/40'
    api_rest: 'link:../api-reference/jmix-rest/index.html'
    git_frontendUi: 'https://github.com/Haulmont/jmix-frontend'
    # end cuba frontend
    minimal-idea-version: '2021.1'
    idea-download-site: 'https://www.jetbrains.com/idea/download/'
    rest-api-open-api: 'https://docs.jmix.io/openapi/1.0/'
    jmix-nightly: 'https://plugins.jetbrains.com/plugins/jmix_nightly/list'
    jmix-plugin-site: 'https://plugins.jetbrains.com/plugin/14340-jmix/versions'
    page-pagination: true
    java_api_url: 'https://docs.jmix.io/api'
    spring-boot-version: '2.5.5'