site:
  title: Jmix 文档
  start_page: jmix:ROOT:intro.adoc
  url: https://docs.jmix.cn/
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: content
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./content/supplemental
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    minimal-idea-version: "2021.1"
    idea-download-site: "https://www.jetbrains.com/idea/download/"
    rest-api-open-api: "https://docs.jmix.io/openapi/1.2/"
    jmix-nightly: "https://plugins.jetbrains.com/plugins/jmix_nightly/list"
    jmix-plugin-site: "https://plugins.jetbrains.com/plugin/14340-jmix/versions"
    page-pagination: true
    java_api_url: "https://docs.jmix.io/api"
    spring-boot-version: "2.6.x"
