site:
  title: Jmix 文档
  start_page: jmix:ROOT:intro.adoc
  url: https://docs.jmix.io/
content:
  sources:
    - url: https://github.com/jmix-framework/jmix-docs.git
      branches:
        - main_zh_cn
        - release_1_x_zh_cn
      start_path: content
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./content/supplemental
asciidoc:
  extensions:
    - asciidoctor-kroki
antora:
  extensions:
    - require: "@jmix-framework/lunr-extension"
      languages: [zh]
      index_latest_only: true
